tt_travel_home:
    path:     /
    defaults: { _controller: TTTravelBundle:Main:index }
    methods: [GET]

tt_travel_search:
    path:   /search
    defaults: { _controller: TTTravelBundle:Main:search }
    methods: [POST]
    
tt_travel_commande:
    path:   /commande/{train}
    defaults: { _controller: TTTravelBundle:Main:commande }
    methods: [GET,POST]
    